"""
bit_coin_teste
DAG auto-generated by Astro Cloud IDE.
"""

from airflow.decorators import dag
from astro import sql as aql
import pandas as pd
import pendulum


@aql.dataframe(task_id="python_1")
def python_1_func():
    return

default_args={
    "owner": "Marcelo Bastos,Open in Cloud IDE",
}

@dag(
    default_args=default_args,
    schedule="0 0 * * *",
    start_date=pendulum.from_format("2025-02-02", "YYYY-MM-DD").in_tz("UTC"),
    catchup=False,
    owner_links={
        "Marcelo Bastos": "mailto:marceloc.bastos@hotmail.com",
        "Open in Cloud IDE": "https://cloud.astronomer.io/cm6no12ys0yvu01l02bn0d5bn/cloud-ide/cm6nobzpl0zai01ivczdi6i60/cm6o9asfb12bs01ivnfozwcf3",
    },
)
def bit_coin_teste():
    python_1 = python_1_func()

dag_obj = bit_coin_teste()
